apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: demodeployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo $(hostname) > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "500m"  
          ports:
            - containerPort: 80

    
