apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: demo1
  labels:
      app.kubernetes.io/name: myapp
spec:
    containers:
    - name: myapp
      image: nginx:latest
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  